clients/ros1/free_fleet_client/CMakeLists.txt, clients/ros1/free_fleet_client/src/Client.cpp, clients/ros1/free_fleet_client/src/Client.hpp, clients/ros1/free_fleet_client/src/tests/test_dds_pub_destination_request.cpp, clients/ros1/free_fleet_client/src/tests/test_dds_pub_mode_request.cpp, clients/ros1/free_fleet_client/src/tests/test_dds_pub_path_request.cpp, clients/ros1/free_fleet_client/src/tests/test_dds_pub_sim_path_request.cpp, clients/ros1/free_fleet_client/src/tests/test_dds_sub_state.cpp
* starts using the new requests and states with `task_id`
* robot state `task_id` returns to empty string when idle
* added task IDs to the testing executables
* using allocs for the testing executables as well for completion
=> Handle task ids

clients/ros1/free_fleet_client/src/Client.cpp, clients/ros1/free_fleet_client/src/Client.hpp, clients/ros1/free_fleet_client/src/main.cpp
this allows `robot_name` to be set from roslaunch files using a `<param>` tag, for example, like this:
```
<param name="robot_name" command="hostname" />
```
=> Override config in rosparam

clients/ros1/free_fleet_client/src/Client.cpp, clients/ros1/free_fleet_client/src/free_fleet/FreeFleet.c, clients/ros1/free_fleet_client/src/free_fleet/FreeFleet.h, clients/ros1/free_fleet_client/src/free_fleet/FreeFleet.idl, clients/ros1/free_fleet_client/src/tests/test_dds_pub_destination_request.cpp, clients/ros1/free_fleet_client/src/tests/test_dds_pub_mode_request.cpp, clients/ros1/free_fleet_client/src/tests/test_dds_pub_path_request.cpp, clients/ros1/free_fleet_client/src/tests/test_dds_pub_sim_path_request.cpp, clients/ros1/free_fleet_client/src/tests/test_dds_sub_state.cpp, servers/ros2/free_fleet_server/src/Server.cpp, servers/ros2/free_fleet_server/src/free_fleet/FreeFleet.c, servers/ros2/free_fleet_server/src/free_fleet/FreeFleet.h, servers/ros2/free_fleet_server/src/free_fleet/FreeFleet.idl
* change destination request `Location` field name from `location` to `destination`, following `rmf_fleet_msgs`
* adding another mode `MODE_GOING_HOME` to the DDS messages
=> DDS message changes

servers/ros2/free_fleet_server/src/Server.hpp, servers/ros2/free_fleet_server/src/main.cpp
* added argument parsing to server
* defaults DDS domain to max of `uint32_t` which is also `DDS_DEFAULT_DOMAIN` in `CycloneDDS`, which goes to 0
* tested working on same machine, time to test with magnis
=> Server arg parse

servers/ros2/free_fleet_server/src/Server.cpp, servers/ros2/free_fleet_server_test/free_fleet_server_test/send_destination_request.py, servers/ros2/free_fleet_server_test/free_fleet_server_test/send_mode_request.py, servers/ros2/free_fleet_server_test/package.xml, servers/ros2/free_fleet_server_test/setup.cfg, servers/ros2/free_fleet_server_test/setup.py
* added 2 scripts for testing the ROS 2 `free_fleet_server`
* found some seg-faulting issues, fixed
=> added some python testing scripts with argparse

clients/ros1/free_fleet_client/src/Client.cpp
* resumes robot when a new request comes in
=> resumes robot after receiving new commands when paused

free_fleet_server_ros2/src/ServerNode.cpp
* quick fix, haven't tested yet
=> added missing transformation to fleet frame

free_fleet_client_ros1/src/ClientNode.cpp
* added back missing implementation of pause-go handling
=> added missing implementation of pausing robot

.github/workflows/build.yaml, README.md
* added `launch.xml` dependency to readme, to fix https://github.com/osrf/free_fleet/issues/34
=> missing launch dependency for xml launch files

ff_examples_ros1/CHANGELOG.rst, ff_examples_ros1/package.xml, ff_examples_ros2/CHANGELOG.rst, ff_examples_ros2/package.xml, ff_rviz_plugins_ros1/CHANGELOG.rst, ff_rviz_plugins_ros1/package.xml, free_fleet/CHANGELOG.rst, free_fleet/package.xml, free_fleet_client_ros1/CHANGELOG.rst, free_fleet_client_ros1/package.xml, free_fleet_server_ros2/CHANGELOG.rst, free_fleet_server_ros2/package.xml
Please have a look at the automatically generated changelogs and correct as needed.
=> Release 1 - Changelogs and version bump

free_fleet/CHANGELOG.rst, free_fleet/CMakeLists.txt, free_fleet/package.xml, free_fleet_client/CHANGELOG.rst, free_fleet_client/package.xml, free_fleet_rviz_plugins/CHANGELOG.rst, free_fleet_rviz_plugins/package.xml
=> Release 1.2.0

.github/workflows/build.yaml
=> Removed examples package from build test in release

free_fleet/CHANGELOG.rst, free_fleet/CMakeLists.txt, free_fleet/package.xml, free_fleet_client/CHANGELOG.rst, free_fleet_client/package.xml, free_fleet_rviz_plugins/CHANGELOG.rst, free_fleet_rviz_plugins/package.xml
(cherry picked from commit c122a3a6be6e342657dd7f2d0fdfb9cede814744)
=> Bumped package versions

free_fleet_client/src/ClientNode.cpp, free_fleet_client/src/ClientNode.hpp, free_fleet_client/src/ClientNodeConfig.cpp, free_fleet_client/src/ClientNodeConfig.hpp, free_fleet_examples/launch/multi_turtlebot3_ff.launch, free_fleet_examples/launch/turtlebot3_world_ff.launch
* Added static level name in configuration
* Removed level name subscription
=> Setting static level name during configuration, removed subscription

free_fleet_client/src/ClientNode.cpp, free_fleet_client/src/ClientNode.hpp, free_fleet_client/src/ClientNodeConfig.cpp, free_fleet_client/src/ClientNodeConfig.hpp
=> Cleaned up cherry pick for examples

README.md, ff_examples_ros1/package.xml
* Updated exec_dependencies to plugins
* Added build instructions for examples
=> Fixed docs to point to specific commit of robot_state_publisher

.github/workflows/build.yaml, README.md
=> Started using open-rmf/rmf_internal_msgs, updated docs and build test

.github/workflows/build.yaml
* Using ROS action-tooling for build workflows on both ROS1 and ROS2
=> Build workflow using action-tooling

README.md, ff_examples_ros1/package.xml
Fixes https://github.com/open-rmf/free_fleet/issues/60.
* Tagged a specific commit of `gazebo_plugins` to be built and used, this will hopefully be helpful for anyone running the examples going forward before the discussions regarding `tf_prefix` are resolved, related to https://github.com/ros/robot_state_publisher/pull/139 and  https://github.com/ros-simulation/gazebo_ros_pkgs/pull/1143
* Updated documentation to clone and build `gazebo_plugins`
=> Tagging a specific commit of gazebo_plugins, updated documentation

free_fleet_server_ros2/src/ServerNode.cpp, free_fleet_server_ros2/src/ServerNode.hpp, free_fleet_server_ros2/src/main.cpp
Fix #103 
Changes should be backward compatible for `foxy` too.
=> Support Galactic

free_fleet_client_ros2/include/free_fleet/ros2/client_node.hpp, free_fleet_client_ros2/src/client_node.cpp
Read and write locks were using a standard mutex which makes the read lock block all threads.
Added additional anonymous blocks for clearing locks.
Changed from WriteLock to ReadLock where it wasn't required.
=> Ros2 client improvements

free_fleet_client_ros2/src/client_node.cpp
Using updated task request to signal that the client doesn't need to wait for remaining time anymore
Fixes: https://github.com/open-rmf/free_fleet/issues/119
Fixed a possibly unintended busy wait for a long period in a while loop, instead of a periodic shorter wait.
Previous implementation performs a busy wait when arriving earlier at a waypoint, and blocks any updates to goals as well. This PR updates the task ids first before the goal paths, which will stop the client from waiting any longer.
=> Fix for busy wait

free_fleet_client_ros2/src/client_node.cpp
response callback signature updated to support galactic and humble. I don't believe this builds on Foxy (haven't tested it).
=> Fix compilation errors for ros2 client on Humble

.github/workflows/build.yaml, ff_examples_ros2/params/turtlebot3_world_burger.yaml, ff_examples_ros2/params/turtlebot3_world_waffle.yaml, ff_examples_ros2/params/turtlebot3_world_waffle_pi.yaml, ff_ros2.repos
Fixes https://github.com/open-rmf/free_fleet/issues/123
Changing robot type from deprecated `differential` to `nav2_amcl::DifferentialMotionModel`
=> Change tb3 robot type to nav2_amcl::DifferentialMotionModel

.github/workflows/build.yaml
Created a matrix to merge the code of the two jobs previously defined.
=> Matrix strategy for build CI

ff_examples_ros1/package.xml, ff_examples_ros2/package.xml, ff_rviz_plugins_ros1/package.xml, free_fleet/package.xml, free_fleet_client_ros1/package.xml, free_fleet_client_ros2/package.xml, free_fleet_server_ros2/package.xml
Bumping version to 1.3.0 for tagging before https://github.com/open-rmf/free_fleet/pull/145 gets merged
=> Bump versions to 1.3.0

.github/docker/minimal-zenoh-bridge-ros2dds/Dockerfile, .github/workflows/e2e-tests.yaml, .github/workflows/nav1-integration-tests.yaml, .github/workflows/nav2-integration-tests.yaml, .github/workflows/nightly.yaml, .github/workflows/unit-tests.yaml, README.md
=> Bump zenoh to 1.3.3

.github/workflows/nightly.yaml
Remove missing requirement step
=> Fix broken nightly workflow file

free_fleet_adapter/free_fleet_adapter/nav2_robot_adapter.py
Fixes member access bug mentioned in https://github.com/open-rmf/free_fleet/issues/200
=> Fix member access error mentioned in #200
